mv bitcoin.csv bitcoin.csv
mv ethereum.csv ethereum.csv
mv ripple.csv ripple.csv
mv dash.csv dash.csv
mv litecoin.csv litecoin.csv
mv iota.csv iota.csv
mv nem.csv nem.csv
mv monero.csv monero.csv
mv neo.csv neo.csv
mv stratis.csv stratis.csv
mv lisk.csv lisk.csv
mv zcash.csv zcash.csv
mv waves.csv waves.csv
mv steem.csv steem.csv
mv bitshares.csv bitshares.csv
mv factom.csv factom.csv
mv decred.csv decred.csv
mv siacoin.csv siacoin.csv
mv dogecoin.csv dogecoin.csv
mv byteball.csv byteball.csv
mv ark.csv ark.csv
mv pivx.csv pivx.csv
mv komodo.csv komodo.csv
mv digibyte.csv digibyte.csv
mv nxt.csv nxt.csv
mv lykke.csv lykke.csv
mv nexus.csv nexus.csv
mv blocknet.csv blocknet.csv
mv ubiq.csv ubiq.csv
mv syscoin.csv syscoin.csv
mv particl.csv particl.csv
mv decent.csv decent.csv
mv asch.csv asch.csv
mv emercoin.csv emercoin.csv
mv peercoin.csv peercoin.csv
mv leocoin.csv leocoin.csv
mv firstcoin.csv firstcoin.csv
mv elastic.csv elastic.csv
mv gulden.csv gulden.csv
mv vertcoin.csv vertcoin.csv
mv zcoin.csv zcoin.csv
mv faircoin.csv faircoin.csv
mv verge.csv verge.csv
mv cloakcoin.csv cloakcoin.csv
mv namecoin.csv namecoin.csv
mv reddcoin.csv reddcoin.csv
mv eb3-coin.csv eb3coin.csv
mv potcoin.csv potcoin.csv
mv viacoin.csv viacoin.csv
mv monacoin.csv monacoin.csv
mv bitbay.csv bitbay.csv
mv expanse.csv expanse.csv
mv ion.csv ion.csv
mv crown.csv crown.csv
mv blackcoin.csv blackcoin.csv
mv peerplays.csv peerplays.csv
mv golos.csv golos.csv
mv skycoin.csv skycoin.csv
mv clams.csv clams.csv
mv omni.csv omni.csv
mv radium.csv radium.csv
mv mooncoin.csv mooncoin.csv
mv nav-coin.csv navcoin.csv
mv sibcoin.csv sibcoin.csv
mv salus.csv salus.csv
mv zencash.csv zencash.csv
mv ybcoin.csv ybcoin.csv
mv raiblocks.csv raiblocks.csv
mv aeon.csv aeon.csv
mv gridcoin.csv gridcoin.csv
mv rubycoin.csv rubycoin.csv
mv shift.csv shift.csv
mv neoscoin.csv neoscoin.csv
mv e-coin.csv ecoin.csv
mv diamond.csv diamond.csv
mv burst.csv burst.csv
mv earthcoin.csv earthcoin.csv
mv voxels.csv voxels.csv
mv lomocoin.csv lomocoin.csv
mv rise.csv rise.csv
mv gambit.csv gambit.csv
mv toacoin.csv toacoin.csv
mv putincoin.csv putincoin.csv
mv vericoin.csv vericoin.csv
mv primecoin.csv primecoin.csv
mv curecoin.csv curecoin.csv
mv sphere.csv sphere.csv
mv htmlcoin.csv htmlcoin.csv
mv dubaicoin.csv dubaicoin.csv
mv prizm.csv prizm.csv
mv musicoin.csv musicoin.csv
mv luckchain.csv luckchain.csv
mv sequence.csv sequence.csv
mv dnotes.csv dnotes.csv
mv vpncoin.csv vpncoin.csv
mv okcash.csv okcash.csv
mv bitsend.csv bitsend.csv
mv mergecoin.csv mergecoin.csv
mv greencoin.csv greencoin.csv
mv vcash.csv vcash.csv
mv blitzcash.csv blitzcash.csv
mv quark.csv quark.csv
mv bitbean.csv bitbean.csv
mv atc-coin.csv atccoin.csv
mv geocoin.csv geocoin.csv
mv megacoin.csv megacoin.csv
mv signatum.csv signatum.csv
mv synergy.csv synergy.csv
mv goldcoin.csv goldcoin.csv
mv bitswift.csv bitswift.csv
mv pinkcoin.csv pinkcoin.csv
mv novacoin.csv novacoin.csv
mv maxcoin.csv maxcoin.csv
mv deeponion.csv deeponion.csv
mv daxxcoin.csv daxxcoin.csv
mv mintcoin.csv mintcoin.csv
mv dynamic.csv dynamic.csv
mv zetacoin.csv zetacoin.csv
mv zennies.csv zennies.csv
mv bata.csv bata.csv
mv compcoin.csv compcoin.csv
mv zclassic.csv zclassic.csv
mv espers.csv espers.csv
mv myriad.csv myriad.csv
mv korecoin.csv korecoin.csv
mv embercoin.csv embercoin.csv
mv dopecoin.csv dopecoin.csv
mv dimecoin.csv dimecoin.csv
mv bitmark.csv bitmark.csv
mv chaincoin.csv chaincoin.csv
mv riecoin.csv riecoin.csv
mv zccoin.csv zccoin.csv
mv atmos.csv atmos.csv
mv smartcash.csv smartcash.csv
mv breakout.csv breakout.csv
mv memetic.csv memetic.csv
mv 2give.csv 2give.csv
mv hempcoin.csv hempcoin.csv
mv adzcoin.csv adzcoin.csv
mv neutron.csv neutron.csv
mv piecoin.csv piecoin.csv
mv zeitcoin.csv zeitcoin.csv
mv 1337.csv 1337.csv
mv hush.csv hush.csv
mv posw-coin.csv poswcoin.csv
mv tagcoin.csv tagcoin.csv
mv vtorrent.csv vtorrent.csv
mv boolberry.csv boolberry.csv
mv crave.csv crave.csv
mv dotcoin.csv dotcoin.csv
mv parkbyte.csv parkbyte.csv
mv visio.csv visio.csv
mv e-gulden.csv egulden.csv
mv ixcoin.csv ixcoin.csv
mv fastcoin.csv fastcoin.csv
mv magi.csv magi.csv
mv centurion.csv centurion.csv
mv sprouts.csv sprouts.csv
mv eternity.csv eternity.csv
mv cream.csv cream.csv
mv audiocoin.csv audiocoin.csv
mv unitus.csv unitus.csv
mv bitcore.csv bitcore.csv
mv fujicoin.csv fujicoin.csv
mv sexcoin.csv sexcoin.csv
mv litedoge.csv litedoge.csv
mv incakoin.csv incakoin.csv
mv 808coin.csv 808coin.csv
mv renos.csv renos.csv
mv tickets.csv tickets.csv
mv bytecent.csv bytecent.csv
mv devcoin.csv devcoin.csv
mv netko.csv netko.csv
mv fimkrypto.csv fimkrypto.csv
mv woodcoin.csv woodcoin.csv
mv linx.csv linx.csv
mv capricoin.csv capricoin.csv
mv happycoin.csv happycoin.csv
mv linda.csv linda.csv
mv xp.csv xp.csv
mv orbitcoin.csv orbitcoin.csv
mv nubits.csv nubits.csv
mv postcoin.csv postcoin.csv
mv netcoin.csv netcoin.csv
mv pakcoin.csv pakcoin.csv
mv iticoin.csv iticoin.csv
mv hitcoin.csv hitcoin.csv
mv unify.csv unify.csv
mv zoin.csv zoin.csv
mv veltor.csv veltor.csv
mv cryptcoin.csv cryptcoin.csv
mv coinonatx.csv coinonatx.csv
mv vsync.csv vsync.csv
mv cachecoin.csv cachecoin.csv
mv 8bit.csv 8bit.csv
mv zurcoin.csv zurcoin.csv
mv denarius.csv denarius.csv
mv das.csv das.csv
mv gcoin.csv gcoin.csv
mv chncoin.csv chncoin.csv
mv zero.csv zero.csv
mv sumokoin.csv sumokoin.csv
mv scorecoin.csv scorecoin.csv
mv hicoin.csv hicoin.csv
mv francs.csv francs.csv
mv malcoin.csv malcoin.csv
mv rupaya.csv rupaya.csv
mv joulecoin.csv joulecoin.csv
mv litebar.csv litebar.csv
mv icoin.csv icoin.csv
mv chancoin.csv chancoin.csv
mv ratecoin.csv ratecoin.csv
mv blakestar.csv blakestar.csv
mv pesobit.csv pesobit.csv
mv blakecoin.csv blakecoin.csv
mv catcoin.csv catcoin.csv
mv kurrent.csv kurrent.csv
mv sojourn.csv sojourn.csv
mv kushcoin.csv kushcoin.csv
mv honey.csv honey.csv
mv berncash.csv berncash.csv
mv solaris.csv solaris.csv
mv acoin.csv acoin.csv
mv rupee.csv rupee.csv
mv marscoin.csv marscoin.csv
mv allion.csv allion.csv
mv coinonat.csv coinonat.csv
mv comet.csv comet.csv
mv nevacoin.csv nevacoin.csv
mv eryllium.csv eryllium.csv
mv veros.csv veros.csv
mv sixeleven.csv sixeleven.csv
mv crevacoin.csv crevacoin.csv
mv doubloon.csv doubloon.csv
mv frazcoin.csv frazcoin.csv
mv creatio.csv creatio.csv
mv onix.csv onix.csv
mv levoplus.csv levoplus.csv
mv slevin.csv slevin.csv
mv wexcoin.csv wexcoin.csv
mv magnum.csv magnum.csv
mv applecoin.csv applecoin.csv
mv enigma.csv enigma.csv
mv asiacoin.csv asiacoin.csv
mv fincoin.csv fincoin.csv
mv yashcoin.csv yashcoin.csv
mv tao.csv tao.csv
mv bluecoin.csv bluecoin.csv
mv octanox.csv octanox.csv
mv moin.csv moin.csv
mv bitradio.csv bitradio.csv
mv bitz.csv bitz.csv
mv metalcoin.csv metalcoin.csv
mv noblecoin.csv noblecoin.csv
mv i0coin.csv i0coin.csv
mv shorty.csv shorty.csv
mv kobocoin.csv kobocoin.csv
mv dashcoin.csv dashcoin.csv
mv 42-coin.csv 42coin.csv
mv britcoin.csv britcoin.csv
mv bitbar.csv bitbar.csv
mv rubies.csv rubies.csv
mv kilocoin.csv kilocoin.csv
mv bitcloud.csv bitcloud.csv
mv piggycoin.csv piggycoin.csv
mv stress.csv stress.csv
mv version.csv version.csv
mv anoncoin.csv anoncoin.csv
mv ambercoin.csv ambercoin.csv
mv ufo-coin.csv ufocoin.csv
mv qubitcoin.csv qubitcoin.csv
mv mazacoin.csv mazacoin.csv
mv cagecoin.csv cagecoin.csv
mv reecoin.csv reecoin.csv
mv gaia.csv gaia.csv
mv slimcoin.csv slimcoin.csv
mv fuelcoin.csv fuelcoin.csv
mv flycoin.csv flycoin.csv
mv bitstar.csv bitstar.csv
mv titcoin.csv titcoin.csv
mv bitcointx.csv bitcointx.csv
mv purevidz.csv purevidz.csv
mv bittokens.csv bittokens.csv
mv lanacoin.csv lanacoin.csv
mv aurumcoin.csv aurumcoin.csv
mv paycoin.csv paycoin.csv
mv mineum.csv mineum.csv
mv elcoin.csv elcoin.csv
mv hodlcoin.csv hodlcoin.csv
mv chesscoin.csv chesscoin.csv
mv tekcoin.csv tekcoin.csv
mv cannacoin.csv cannacoin.csv
mv universe.csv universe.csv
mv pipcoin.csv pipcoin.csv
mv prime-xi.csv primexi.csv
mv kibicoin.csv kibicoin.csv
mv lottocoin.csv lottocoin.csv
mv freicoin.csv freicoin.csv
mv joincoin.csv joincoin.csv
mv c-bit.csv cbit.csv
mv mojocoin.csv mojocoin.csv
mv timereum.csv timereum.csv
mv octocoin.csv octocoin.csv
mv valorbit.csv valorbit.csv
mv corgicoin.csv corgicoin.csv
mv eurocoin.csv eurocoin.csv
mv darsek.csv darsek.csv
mv unicoin.csv unicoin.csv
mv wayguide.csv wayguide.csv
mv bunnycoin.csv bunnycoin.csv
mv gameunits.csv gameunits.csv
mv swing.csv swing.csv
mv evil-coin.csv evilcoin.csv
mv yacoin.csv yacoin.csv
mv nyancoin.csv nyancoin.csv
mv icobid.csv icobid.csv
mv cypher.csv cypher.csv
mv b3coin.csv b3coin.csv
mv gpu-coin.csv gpucoin.csv
mv dreamcoin.csv dreamcoin.csv
mv digicube.csv digicube.csv
mv cannation.csv cannation.csv
mv prcoin.csv prcoin.csv
mv aricoin.csv aricoin.csv
mv vector.csv vector.csv
mv grantcoin.csv grantcoin.csv
mv bigup.csv bigup.csv
mv franko.csv franko.csv
mv guncoin.csv guncoin.csv
mv ucoin.csv ucoin.csv
mv px.csv px.csv
mv bitzeny.csv bitzeny.csv
mv jin-coin.csv jincoin.csv
mv wmcoin.csv wmcoin.csv
mv x-coin.csv xcoin.csv
mv argentum.csv argentum.csv
mv chronos.csv chronos.csv
mv compucoin.csv compucoin.csv
mv paycon.csv paycon.csv
mv electra.csv electra.csv
mv rimbit.csv rimbit.csv
mv sling.csv sling.csv
mv spots.csv spots.csv
mv allsafe.csv allsafe.csv
mv islacoin.csv islacoin.csv
mv bipcoin.csv bipcoin.csv
mv redcoin.csv redcoin.csv
mv gapcoin.csv gapcoin.csv
mv money.csv money.csv
mv halcyon.csv halcyon.csv
mv alexium.csv alexium.csv
mv soilcoin.csv soilcoin.csv
mv quatloo.csv quatloo.csv
mv 23-skidoo.csv 23skidoo.csv
mv boostcoin.csv boostcoin.csv
mv bumbacoin.csv bumbacoin.csv
mv evotion.csv evotion.csv
mv arbit.csv arbit.csv
mv ponzicoin.csv ponzicoin.csv
mv debitcoin.csv debitcoin.csv
mv torcoin.csv torcoin.csv
mv wyvern.csv wyvern.csv
mv pulse.csv pulse.csv
mv bbqcoin.csv bbqcoin.csv
mv hexx.csv hexx.csv
mv bnrtxcoin.csv bnrtxcoin.csv
mv jewels.csv jewels.csv
mv uro.csv uro.csv
mv songcoin.csv songcoin.csv
mv sooncoin.csv sooncoin.csv
mv crypto.csv crypto.csv
mv orlycoin.csv orlycoin.csv
mv photon.csv photon.csv
mv milocoin.csv milocoin.csv
mv plncoin.csv plncoin.csv
mv leacoin.csv leacoin.csv
mv firecoin.csv firecoin.csv
mv iconic.csv iconic.csv
mv steps.csv steps.csv
mv hirocoin.csv hirocoin.csv
mv macron.csv macron.csv
mv cashcoin.csv cashcoin.csv
mv mindcoin.csv mindcoin.csv
mv beatcoin.csv beatcoin.csv
mv cabbage.csv cabbage.csv
mv bitquark.csv bitquark.csv
mv impact.csv impact.csv
mv ecocoin.csv ecocoin.csv
mv tagrcoin.csv tagrcoin.csv
mv neuro.csv neuro.csv
mv destiny.csv destiny.csv
mv bitcoal.csv bitcoal.csv
mv luna-coin.csv lunacoin.csv
mv fuzzballs.csv fuzzballs.csv
mv blackstar.csv blackstar.csv
mv ganjacoin.csv ganjacoin.csv
mv dappster.csv dappster.csv
mv tajcoin.csv tajcoin.csv
mv briacoin.csv briacoin.csv
mv ibank.csv ibank.csv
mv warp.csv warp.csv
mv ego.csv ego.csv
mv dpay.csv dpay.csv
mv xonecoin.csv xonecoin.csv
mv blazecoin.csv blazecoin.csv
mv jobscoin.csv jobscoin.csv
mv bowscoin.csv bowscoin.csv
mv revenu.csv revenu.csv
mv posex.csv posex.csv
mv crtcoin.csv crtcoin.csv
mv letitride.csv letitride.csv
mv litecred.csv litecred.csv
mv abncoin.csv abncoin.csv
mv zonecoin.csv zonecoin.csv
mv rsgpcoin.csv rsgpcoin.csv
mv shilling.csv shilling.csv
mv concoin.csv concoin.csv
mv argus.csv argus.csv
mv rawcoin.csv rawcoin.csv
mv geertcoin.csv geertcoin.csv
mv sydpak.csv sydpak.csv
mv biobar.csv biobar.csv
mv p7coin.csv p7coin.csv
mv 1credit.csv 1credit.csv
mv bitvolt.csv bitvolt.csv
mv nodecoin.csv nodecoin.csv
mv elysium.csv elysium.csv
mv environ.csv environ.csv
mv powercoin.csv powercoin.csv
mv pizzacoin.csv pizzacoin.csv
mv gxshares.csv gxshares.csv
mv hshare.csv hshare.csv
mv vechain.csv vechain.csv
mv pura.csv pura.csv
mv lepaoquan.csv lepaoquan.csv
mv infchain.csv infchain.csv
mv fargocoin.csv fargocoin.csv
mv bagcoin.csv bagcoin.csv
mv voyacoin.csv voyacoin.csv
mv krypstal.csv krypstal.csv
mv gycoin.csv gycoin.csv
mv bitok.csv bitok.csv
mv deuscoin.csv deuscoin.csv
mv clubcoin.csv clubcoin.csv
mv aseancoin.csv aseancoin.csv
mv xtd-coin.csv xtdcoin.csv
mv fibocoins.csv fibocoins.csv
mv dhg.csv dhg.csv
mv bitdeal.csv bitdeal.csv
mv usde.csv usde.csv
mv wa-space.csv waspace.csv
mv axfunds.csv axfunds.csv
mv ur.csv ur.csv
mv adcoin.csv adcoin.csv
mv falcoin.csv falcoin.csv
mv atmcoin.csv atmcoin.csv
mv mind-gene.csv mindgene.csv
mv hyper.csv hyper.csv
mv hbcoin.csv hbcoin.csv
mv rublebit.csv rublebit.csv
mv flash.csv flash.csv
mv 9coin.csv 9coin.csv
mv excelcoin.csv excelcoin.csv
mv coupecoin.csv coupecoin.csv
mv paccoin.csv paccoin.csv
mv gulfcoin.csv gulfcoin.csv
mv teracoin.csv teracoin.csv
mv animecoin.csv animecoin.csv
mv alpacoin.csv alpacoin.csv
mv landcoin.csv landcoin.csv
mv moneycoin.csv moneycoin.csv
mv edrcoin.csv edrcoin.csv
mv project-x.csv projectx.csv
mv quotient.csv quotient.csv
mv yogold.csv yogold.csv
mv xde-ii.csv xdeii.csv
mv utacoin.csv utacoin.csv
mv bitcedi.csv bitcedi.csv
mv marxcoin.csv marxcoin.csv
mv sync.csv sync.csv
mv t-coin.csv tcoin.csv
mv axiom.csv axiom.csv
mv opal.csv opal.csv
mv aces.csv aces.csv
mv sharkcoin.csv sharkcoin.csv
mv braincoin.csv braincoin.csv
mv birds.csv birds.csv
mv dashs.csv dashs.csv
mv wink.csv wink.csv
mv bestchain.csv bestchain.csv
mv omicron.csv omicron.csv
mv zsecoin.csv zsecoin.csv
mv fazzcoin.csv fazzcoin.csv
mv primulon.csv primulon.csv
mv opescoin.csv opescoin.csv
mv irishcoin.csv irishcoin.csv
mv moneta.csv moneta.csv
mv miyucoin.csv miyucoin.csv
mv paypeer.csv paypeer.csv
mv elacoin.csv elacoin.csv
mv topcoin.csv topcoin.csv
mv motocoin.csv motocoin.csv
mv kashhcoin.csv kashhcoin.csv
mv yescoin.csv yescoin.csv
mv picoin.csv picoin.csv
mv betacoin.csv betacoin.csv
mv royalties.csv royalties.csv
mv peepcoin.csv peepcoin.csv
mv quebecoin.csv quebecoin.csv
mv cubits.csv cubits.csv
mv cheapcoin.csv cheapcoin.csv
mv lathaan.csv lathaan.csv
mv quartz.csv quartz.csv
mv mavro.csv mavro.csv
mv futcoin.csv futcoin.csv
mv batcoin.csv batcoin.csv
mv clinton.csv clinton.csv
mv lepen.csv lepen.csv
mv pokecoin.csv pokecoin.csv
mv karmacoin.csv karmacoin.csv
mv draftcoin.csv draftcoin.csv
mv dubstep.csv dubstep.csv
mv qora.csv qora.csv
mv bitgem.csv bitgem.csv
mv shacoin.csv shacoin.csv
mv safecoin.csv safecoin.csv
mv rcoin.csv rcoin.csv
mv richcoin.csv richcoin.csv
mv skeincoin.csv skeincoin.csv
mv thecreed.csv thecreed.csv
mv royalcoin.csv royalcoin.csv
mv shellcoin.csv shellcoin.csv
mv cybercoin.csv cybercoin.csv
mv microcoin.csv microcoin.csv
mv eggcoin.csv eggcoin.csv
mv cashme.csv cashme.csv
mv ocow.csv ocow.csv
mv darklisk.csv darklisk.csv
mv bongger.csv bongger.csv
mv rhfcoin.csv rhfcoin.csv
mv netbit.csv netbit.csv
mv soulcoin.csv soulcoin.csv
mv x2.csv x2.csv
mv shellpay.csv shellpay.csv
mv tyrocoin.csv tyrocoin.csv
mv huncoin.csv huncoin.csv
mv teamup.csv teamup.csv
mv mmxvi.csv mmxvi.csv
mv ugain.csv ugain.csv
mv gambleo.csv gambleo.csv
mv golfcoin.csv golfcoin.csv
mv xaucoin.csv xaucoin.csv
mv asiccoin.csv asiccoin.csv
mv pinkdog.csv pinkdog.csv
mv operand.csv operand.csv
mv wowcoin.csv wowcoin.csv
mv btcgold.csv btcgold.csv
mv regacoin.csv regacoin.csv
mv avoncoin.csv avoncoin.csv
mv uncoin.csv uncoin.csv
