csvtojson bitcoin.csv > bitcoin.json
csvtojson ethereum.csv > ethereum.json
csvtojson ripple.csv > ripple.json
csvtojson dash.csv > dash.json
csvtojson litecoin.csv > litecoin.json
csvtojson iota.csv > iota.json
csvtojson nem.csv > nem.json
csvtojson monero.csv > monero.json
csvtojson neo.csv > neo.json
csvtojson stratis.csv > stratis.json
csvtojson lisk.csv > lisk.json
csvtojson zcash.csv > zcash.json
csvtojson waves.csv > waves.json
csvtojson steem.csv > steem.json
csvtojson bitshares.csv > bitshares.json
csvtojson factom.csv > factom.json
csvtojson decred.csv > decred.json
csvtojson siacoin.csv > siacoin.json
csvtojson dogecoin.csv > dogecoin.json
csvtojson byteball.csv > byteball.json
csvtojson ark.csv > ark.json
csvtojson pivx.csv > pivx.json
csvtojson komodo.csv > komodo.json
csvtojson digibyte.csv > digibyte.json
csvtojson nxt.csv > nxt.json
csvtojson lykke.csv > lykke.json
csvtojson nexus.csv > nexus.json
csvtojson blocknet.csv > blocknet.json
csvtojson ubiq.csv > ubiq.json
csvtojson syscoin.csv > syscoin.json
csvtojson particl.csv > particl.json
csvtojson decent.csv > decent.json
csvtojson asch.csv > asch.json
csvtojson emercoin.csv > emercoin.json
csvtojson peercoin.csv > peercoin.json
csvtojson leocoin.csv > leocoin.json
csvtojson firstcoin.csv > firstcoin.json
csvtojson elastic.csv > elastic.json
csvtojson gulden.csv > gulden.json
csvtojson vertcoin.csv > vertcoin.json
csvtojson zcoin.csv > zcoin.json
csvtojson faircoin.csv > faircoin.json
csvtojson verge.csv > verge.json
csvtojson cloakcoin.csv > cloakcoin.json
csvtojson namecoin.csv > namecoin.json
csvtojson reddcoin.csv > reddcoin.json
csvtojson eb3coin.csv > eb3coin.json
csvtojson potcoin.csv > potcoin.json
csvtojson viacoin.csv > viacoin.json
csvtojson monacoin.csv > monacoin.json
csvtojson bitbay.csv > bitbay.json
csvtojson expanse.csv > expanse.json
csvtojson ion.csv > ion.json
csvtojson crown.csv > crown.json
csvtojson blackcoin.csv > blackcoin.json
csvtojson peerplays.csv > peerplays.json
csvtojson golos.csv > golos.json
csvtojson skycoin.csv > skycoin.json
csvtojson clams.csv > clams.json
csvtojson omni.csv > omni.json
csvtojson radium.csv > radium.json
csvtojson mooncoin.csv > mooncoin.json
csvtojson navcoin.csv > navcoin.json
csvtojson sibcoin.csv > sibcoin.json
csvtojson salus.csv > salus.json
csvtojson zencash.csv > zencash.json
csvtojson ybcoin.csv > ybcoin.json
csvtojson raiblocks.csv > raiblocks.json
csvtojson aeon.csv > aeon.json
csvtojson gridcoin.csv > gridcoin.json
csvtojson rubycoin.csv > rubycoin.json
csvtojson shift.csv > shift.json
csvtojson neoscoin.csv > neoscoin.json
csvtojson ecoin.csv > ecoin.json
csvtojson diamond.csv > diamond.json
csvtojson burst.csv > burst.json
csvtojson earthcoin.csv > earthcoin.json
csvtojson voxels.csv > voxels.json
csvtojson lomocoin.csv > lomocoin.json
csvtojson rise.csv > rise.json
csvtojson gambit.csv > gambit.json
csvtojson toacoin.csv > toacoin.json
csvtojson putincoin.csv > putincoin.json
csvtojson vericoin.csv > vericoin.json
csvtojson primecoin.csv > primecoin.json
csvtojson curecoin.csv > curecoin.json
csvtojson sphere.csv > sphere.json
csvtojson htmlcoin.csv > htmlcoin.json
csvtojson dubaicoin.csv > dubaicoin.json
csvtojson prizm.csv > prizm.json
csvtojson musicoin.csv > musicoin.json
csvtojson luckchain.csv > luckchain.json
csvtojson sequence.csv > sequence.json
csvtojson dnotes.csv > dnotes.json
csvtojson vpncoin.csv > vpncoin.json
csvtojson okcash.csv > okcash.json
csvtojson bitsend.csv > bitsend.json
csvtojson mergecoin.csv > mergecoin.json
csvtojson greencoin.csv > greencoin.json
csvtojson vcash.csv > vcash.json
csvtojson blitzcash.csv > blitzcash.json
csvtojson quark.csv > quark.json
csvtojson bitbean.csv > bitbean.json
csvtojson atccoin.csv > atccoin.json
csvtojson geocoin.csv > geocoin.json
csvtojson megacoin.csv > megacoin.json
csvtojson signatum.csv > signatum.json
csvtojson synergy.csv > synergy.json
csvtojson goldcoin.csv > goldcoin.json
csvtojson bitswift.csv > bitswift.json
csvtojson pinkcoin.csv > pinkcoin.json
csvtojson novacoin.csv > novacoin.json
csvtojson maxcoin.csv > maxcoin.json
csvtojson deeponion.csv > deeponion.json
csvtojson daxxcoin.csv > daxxcoin.json
csvtojson mintcoin.csv > mintcoin.json
csvtojson dynamic.csv > dynamic.json
csvtojson zetacoin.csv > zetacoin.json
csvtojson zennies.csv > zennies.json
csvtojson bata.csv > bata.json
csvtojson compcoin.csv > compcoin.json
csvtojson zclassic.csv > zclassic.json
csvtojson espers.csv > espers.json
csvtojson myriad.csv > myriad.json
csvtojson korecoin.csv > korecoin.json
csvtojson embercoin.csv > embercoin.json
csvtojson dopecoin.csv > dopecoin.json
csvtojson dimecoin.csv > dimecoin.json
csvtojson bitmark.csv > bitmark.json
csvtojson chaincoin.csv > chaincoin.json
csvtojson riecoin.csv > riecoin.json
csvtojson zccoin.csv > zccoin.json
csvtojson atmos.csv > atmos.json
csvtojson smartcash.csv > smartcash.json
csvtojson breakout.csv > breakout.json
csvtojson memetic.csv > memetic.json
csvtojson 2give.csv > 2give.json
csvtojson hempcoin.csv > hempcoin.json
csvtojson adzcoin.csv > adzcoin.json
csvtojson neutron.csv > neutron.json
csvtojson piecoin.csv > piecoin.json
csvtojson zeitcoin.csv > zeitcoin.json
csvtojson 1337.csv > 1337.json
csvtojson hush.csv > hush.json
csvtojson poswcoin.csv > poswcoin.json
csvtojson tagcoin.csv > tagcoin.json
csvtojson vtorrent.csv > vtorrent.json
csvtojson boolberry.csv > boolberry.json
csvtojson crave.csv > crave.json
csvtojson dotcoin.csv > dotcoin.json
csvtojson parkbyte.csv > parkbyte.json
csvtojson visio.csv > visio.json
csvtojson egulden.csv > egulden.json
csvtojson ixcoin.csv > ixcoin.json
csvtojson fastcoin.csv > fastcoin.json
csvtojson magi.csv > magi.json
csvtojson centurion.csv > centurion.json
csvtojson sprouts.csv > sprouts.json
csvtojson eternity.csv > eternity.json
csvtojson cream.csv > cream.json
csvtojson audiocoin.csv > audiocoin.json
csvtojson unitus.csv > unitus.json
csvtojson bitcore.csv > bitcore.json
csvtojson fujicoin.csv > fujicoin.json
csvtojson sexcoin.csv > sexcoin.json
csvtojson litedoge.csv > litedoge.json
csvtojson incakoin.csv > incakoin.json
csvtojson 808coin.csv > 808coin.json
csvtojson renos.csv > renos.json
csvtojson tickets.csv > tickets.json
csvtojson bytecent.csv > bytecent.json
csvtojson devcoin.csv > devcoin.json
csvtojson netko.csv > netko.json
csvtojson fimkrypto.csv > fimkrypto.json
csvtojson woodcoin.csv > woodcoin.json
csvtojson linx.csv > linx.json
csvtojson capricoin.csv > capricoin.json
csvtojson happycoin.csv > happycoin.json
csvtojson linda.csv > linda.json
csvtojson xp.csv > xp.json
csvtojson orbitcoin.csv > orbitcoin.json
csvtojson nubits.csv > nubits.json
csvtojson postcoin.csv > postcoin.json
csvtojson netcoin.csv > netcoin.json
csvtojson pakcoin.csv > pakcoin.json
csvtojson iticoin.csv > iticoin.json
csvtojson hitcoin.csv > hitcoin.json
csvtojson unify.csv > unify.json
csvtojson zoin.csv > zoin.json
csvtojson veltor.csv > veltor.json
csvtojson cryptcoin.csv > cryptcoin.json
csvtojson coinonatx.csv > coinonatx.json
csvtojson vsync.csv > vsync.json
csvtojson cachecoin.csv > cachecoin.json
csvtojson 8bit.csv > 8bit.json
csvtojson zurcoin.csv > zurcoin.json
csvtojson denarius.csv > denarius.json
csvtojson das.csv > das.json
csvtojson gcoin.csv > gcoin.json
csvtojson chncoin.csv > chncoin.json
csvtojson zero.csv > zero.json
csvtojson sumokoin.csv > sumokoin.json
csvtojson scorecoin.csv > scorecoin.json
csvtojson hicoin.csv > hicoin.json
csvtojson francs.csv > francs.json
csvtojson malcoin.csv > malcoin.json
csvtojson rupaya.csv > rupaya.json
csvtojson joulecoin.csv > joulecoin.json
csvtojson litebar.csv > litebar.json
csvtojson icoin.csv > icoin.json
csvtojson chancoin.csv > chancoin.json
csvtojson ratecoin.csv > ratecoin.json
csvtojson blakestar.csv > blakestar.json
csvtojson pesobit.csv > pesobit.json
csvtojson blakecoin.csv > blakecoin.json
csvtojson catcoin.csv > catcoin.json
csvtojson kurrent.csv > kurrent.json
csvtojson sojourn.csv > sojourn.json
csvtojson kushcoin.csv > kushcoin.json
csvtojson honey.csv > honey.json
csvtojson berncash.csv > berncash.json
csvtojson solaris.csv > solaris.json
csvtojson acoin.csv > acoin.json
csvtojson rupee.csv > rupee.json
csvtojson marscoin.csv > marscoin.json
csvtojson allion.csv > allion.json
csvtojson coinonat.csv > coinonat.json
csvtojson comet.csv > comet.json
csvtojson nevacoin.csv > nevacoin.json
csvtojson eryllium.csv > eryllium.json
csvtojson veros.csv > veros.json
csvtojson sixeleven.csv > sixeleven.json
csvtojson crevacoin.csv > crevacoin.json
csvtojson doubloon.csv > doubloon.json
csvtojson frazcoin.csv > frazcoin.json
csvtojson creatio.csv > creatio.json
csvtojson onix.csv > onix.json
csvtojson levoplus.csv > levoplus.json
csvtojson slevin.csv > slevin.json
csvtojson wexcoin.csv > wexcoin.json
csvtojson magnum.csv > magnum.json
csvtojson applecoin.csv > applecoin.json
csvtojson enigma.csv > enigma.json
csvtojson asiacoin.csv > asiacoin.json
csvtojson fincoin.csv > fincoin.json
csvtojson yashcoin.csv > yashcoin.json
csvtojson tao.csv > tao.json
csvtojson bluecoin.csv > bluecoin.json
csvtojson octanox.csv > octanox.json
csvtojson moin.csv > moin.json
csvtojson bitradio.csv > bitradio.json
csvtojson bitz.csv > bitz.json
csvtojson metalcoin.csv > metalcoin.json
csvtojson noblecoin.csv > noblecoin.json
csvtojson i0coin.csv > i0coin.json
csvtojson shorty.csv > shorty.json
csvtojson kobocoin.csv > kobocoin.json
csvtojson dashcoin.csv > dashcoin.json
csvtojson 42coin.csv > 42coin.json
csvtojson britcoin.csv > britcoin.json
csvtojson bitbar.csv > bitbar.json
csvtojson rubies.csv > rubies.json
csvtojson kilocoin.csv > kilocoin.json
csvtojson bitcloud.csv > bitcloud.json
csvtojson piggycoin.csv > piggycoin.json
csvtojson stress.csv > stress.json
csvtojson version.csv > version.json
csvtojson anoncoin.csv > anoncoin.json
csvtojson ambercoin.csv > ambercoin.json
csvtojson ufocoin.csv > ufocoin.json
csvtojson qubitcoin.csv > qubitcoin.json
csvtojson mazacoin.csv > mazacoin.json
csvtojson cagecoin.csv > cagecoin.json
csvtojson reecoin.csv > reecoin.json
csvtojson gaia.csv > gaia.json
csvtojson slimcoin.csv > slimcoin.json
csvtojson fuelcoin.csv > fuelcoin.json
csvtojson flycoin.csv > flycoin.json
csvtojson bitstar.csv > bitstar.json
csvtojson titcoin.csv > titcoin.json
csvtojson bitcointx.csv > bitcointx.json
csvtojson purevidz.csv > purevidz.json
csvtojson bittokens.csv > bittokens.json
csvtojson lanacoin.csv > lanacoin.json
csvtojson aurumcoin.csv > aurumcoin.json
csvtojson paycoin.csv > paycoin.json
csvtojson mineum.csv > mineum.json
csvtojson elcoin.csv > elcoin.json
csvtojson hodlcoin.csv > hodlcoin.json
csvtojson chesscoin.csv > chesscoin.json
csvtojson tekcoin.csv > tekcoin.json
csvtojson cannacoin.csv > cannacoin.json
csvtojson universe.csv > universe.json
csvtojson pipcoin.csv > pipcoin.json
csvtojson primexi.csv > primexi.json
csvtojson kibicoin.csv > kibicoin.json
csvtojson lottocoin.csv > lottocoin.json
csvtojson freicoin.csv > freicoin.json
csvtojson joincoin.csv > joincoin.json
csvtojson cbit.csv > cbit.json
csvtojson mojocoin.csv > mojocoin.json
csvtojson timereum.csv > timereum.json
csvtojson octocoin.csv > octocoin.json
csvtojson valorbit.csv > valorbit.json
csvtojson corgicoin.csv > corgicoin.json
csvtojson eurocoin.csv > eurocoin.json
csvtojson darsek.csv > darsek.json
csvtojson unicoin.csv > unicoin.json
csvtojson wayguide.csv > wayguide.json
csvtojson bunnycoin.csv > bunnycoin.json
csvtojson gameunits.csv > gameunits.json
csvtojson swing.csv > swing.json
csvtojson evilcoin.csv > evilcoin.json
csvtojson yacoin.csv > yacoin.json
csvtojson nyancoin.csv > nyancoin.json
csvtojson icobid.csv > icobid.json
csvtojson cypher.csv > cypher.json
csvtojson b3coin.csv > b3coin.json
csvtojson gpucoin.csv > gpucoin.json
csvtojson dreamcoin.csv > dreamcoin.json
csvtojson digicube.csv > digicube.json
csvtojson cannation.csv > cannation.json
csvtojson prcoin.csv > prcoin.json
csvtojson aricoin.csv > aricoin.json
csvtojson vector.csv > vector.json
csvtojson grantcoin.csv > grantcoin.json
csvtojson bigup.csv > bigup.json
csvtojson franko.csv > franko.json
csvtojson guncoin.csv > guncoin.json
csvtojson ucoin.csv > ucoin.json
csvtojson px.csv > px.json
csvtojson bitzeny.csv > bitzeny.json
csvtojson jincoin.csv > jincoin.json
csvtojson wmcoin.csv > wmcoin.json
csvtojson xcoin.csv > xcoin.json
csvtojson argentum.csv > argentum.json
csvtojson chronos.csv > chronos.json
csvtojson compucoin.csv > compucoin.json
csvtojson paycon.csv > paycon.json
csvtojson electra.csv > electra.json
csvtojson rimbit.csv > rimbit.json
csvtojson sling.csv > sling.json
csvtojson spots.csv > spots.json
csvtojson allsafe.csv > allsafe.json
csvtojson islacoin.csv > islacoin.json
csvtojson bipcoin.csv > bipcoin.json
csvtojson redcoin.csv > redcoin.json
csvtojson gapcoin.csv > gapcoin.json
csvtojson money.csv > money.json
csvtojson halcyon.csv > halcyon.json
csvtojson alexium.csv > alexium.json
csvtojson soilcoin.csv > soilcoin.json
csvtojson quatloo.csv > quatloo.json
csvtojson 23skidoo.csv > 23skidoo.json
csvtojson boostcoin.csv > boostcoin.json
csvtojson bumbacoin.csv > bumbacoin.json
csvtojson evotion.csv > evotion.json
csvtojson arbit.csv > arbit.json
csvtojson ponzicoin.csv > ponzicoin.json
csvtojson debitcoin.csv > debitcoin.json
csvtojson torcoin.csv > torcoin.json
csvtojson wyvern.csv > wyvern.json
csvtojson pulse.csv > pulse.json
csvtojson bbqcoin.csv > bbqcoin.json
csvtojson hexx.csv > hexx.json
csvtojson bnrtxcoin.csv > bnrtxcoin.json
csvtojson jewels.csv > jewels.json
csvtojson uro.csv > uro.json
csvtojson songcoin.csv > songcoin.json
csvtojson sooncoin.csv > sooncoin.json
csvtojson crypto.csv > crypto.json
csvtojson orlycoin.csv > orlycoin.json
csvtojson photon.csv > photon.json
csvtojson milocoin.csv > milocoin.json
csvtojson plncoin.csv > plncoin.json
csvtojson leacoin.csv > leacoin.json
csvtojson firecoin.csv > firecoin.json
csvtojson iconic.csv > iconic.json
csvtojson steps.csv > steps.json
csvtojson hirocoin.csv > hirocoin.json
csvtojson macron.csv > macron.json
csvtojson cashcoin.csv > cashcoin.json
csvtojson mindcoin.csv > mindcoin.json
csvtojson beatcoin.csv > beatcoin.json
csvtojson cabbage.csv > cabbage.json
csvtojson bitquark.csv > bitquark.json
csvtojson impact.csv > impact.json
csvtojson ecocoin.csv > ecocoin.json
csvtojson tagrcoin.csv > tagrcoin.json
csvtojson neuro.csv > neuro.json
csvtojson destiny.csv > destiny.json
csvtojson bitcoal.csv > bitcoal.json
csvtojson lunacoin.csv > lunacoin.json
csvtojson fuzzballs.csv > fuzzballs.json
csvtojson blackstar.csv > blackstar.json
csvtojson ganjacoin.csv > ganjacoin.json
csvtojson dappster.csv > dappster.json
csvtojson tajcoin.csv > tajcoin.json
csvtojson briacoin.csv > briacoin.json
csvtojson ibank.csv > ibank.json
csvtojson warp.csv > warp.json
csvtojson ego.csv > ego.json
csvtojson dpay.csv > dpay.json
csvtojson xonecoin.csv > xonecoin.json
csvtojson blazecoin.csv > blazecoin.json
csvtojson jobscoin.csv > jobscoin.json
csvtojson bowscoin.csv > bowscoin.json
csvtojson revenu.csv > revenu.json
csvtojson posex.csv > posex.json
csvtojson crtcoin.csv > crtcoin.json
csvtojson letitride.csv > letitride.json
csvtojson litecred.csv > litecred.json
csvtojson abncoin.csv > abncoin.json
csvtojson zonecoin.csv > zonecoin.json
csvtojson rsgpcoin.csv > rsgpcoin.json
csvtojson shilling.csv > shilling.json
csvtojson concoin.csv > concoin.json
csvtojson argus.csv > argus.json
csvtojson rawcoin.csv > rawcoin.json
csvtojson geertcoin.csv > geertcoin.json
csvtojson sydpak.csv > sydpak.json
csvtojson biobar.csv > biobar.json
csvtojson p7coin.csv > p7coin.json
csvtojson 1credit.csv > 1credit.json
csvtojson bitvolt.csv > bitvolt.json
csvtojson nodecoin.csv > nodecoin.json
csvtojson elysium.csv > elysium.json
csvtojson environ.csv > environ.json
csvtojson powercoin.csv > powercoin.json
csvtojson pizzacoin.csv > pizzacoin.json
csvtojson gxshares.csv > gxshares.json
csvtojson hshare.csv > hshare.json
csvtojson vechain.csv > vechain.json
csvtojson pura.csv > pura.json
csvtojson lepaoquan.csv > lepaoquan.json
csvtojson infchain.csv > infchain.json
csvtojson fargocoin.csv > fargocoin.json
csvtojson bagcoin.csv > bagcoin.json
csvtojson voyacoin.csv > voyacoin.json
csvtojson krypstal.csv > krypstal.json
csvtojson gycoin.csv > gycoin.json
csvtojson bitok.csv > bitok.json
csvtojson deuscoin.csv > deuscoin.json
csvtojson clubcoin.csv > clubcoin.json
csvtojson aseancoin.csv > aseancoin.json
csvtojson xtdcoin.csv > xtdcoin.json
csvtojson fibocoins.csv > fibocoins.json
csvtojson dhg.csv > dhg.json
csvtojson bitdeal.csv > bitdeal.json
csvtojson usde.csv > usde.json
csvtojson waspace.csv > waspace.json
csvtojson axfunds.csv > axfunds.json
csvtojson ur.csv > ur.json
csvtojson adcoin.csv > adcoin.json
csvtojson falcoin.csv > falcoin.json
csvtojson atmcoin.csv > atmcoin.json
csvtojson mindgene.csv > mindgene.json
csvtojson hyper.csv > hyper.json
csvtojson hbcoin.csv > hbcoin.json
csvtojson rublebit.csv > rublebit.json
csvtojson flash.csv > flash.json
csvtojson 9coin.csv > 9coin.json
csvtojson excelcoin.csv > excelcoin.json
csvtojson coupecoin.csv > coupecoin.json
csvtojson paccoin.csv > paccoin.json
csvtojson gulfcoin.csv > gulfcoin.json
csvtojson teracoin.csv > teracoin.json
csvtojson animecoin.csv > animecoin.json
csvtojson alpacoin.csv > alpacoin.json
csvtojson landcoin.csv > landcoin.json
csvtojson moneycoin.csv > moneycoin.json
csvtojson edrcoin.csv > edrcoin.json
csvtojson projectx.csv > projectx.json
csvtojson quotient.csv > quotient.json
csvtojson yogold.csv > yogold.json
csvtojson xdeii.csv > xdeii.json
csvtojson utacoin.csv > utacoin.json
csvtojson bitcedi.csv > bitcedi.json
csvtojson marxcoin.csv > marxcoin.json
csvtojson sync.csv > sync.json
csvtojson tcoin.csv > tcoin.json
csvtojson axiom.csv > axiom.json
csvtojson opal.csv > opal.json
csvtojson aces.csv > aces.json
csvtojson sharkcoin.csv > sharkcoin.json
csvtojson braincoin.csv > braincoin.json
csvtojson birds.csv > birds.json
csvtojson dashs.csv > dashs.json
csvtojson wink.csv > wink.json
csvtojson bestchain.csv > bestchain.json
csvtojson omicron.csv > omicron.json
csvtojson zsecoin.csv > zsecoin.json
csvtojson fazzcoin.csv > fazzcoin.json
csvtojson primulon.csv > primulon.json
csvtojson opescoin.csv > opescoin.json
csvtojson irishcoin.csv > irishcoin.json
csvtojson moneta.csv > moneta.json
csvtojson miyucoin.csv > miyucoin.json
csvtojson paypeer.csv > paypeer.json
csvtojson elacoin.csv > elacoin.json
csvtojson topcoin.csv > topcoin.json
csvtojson motocoin.csv > motocoin.json
csvtojson kashhcoin.csv > kashhcoin.json
csvtojson yescoin.csv > yescoin.json
csvtojson picoin.csv > picoin.json
csvtojson betacoin.csv > betacoin.json
csvtojson royalties.csv > royalties.json
csvtojson peepcoin.csv > peepcoin.json
csvtojson quebecoin.csv > quebecoin.json
csvtojson cubits.csv > cubits.json
csvtojson cheapcoin.csv > cheapcoin.json
csvtojson lathaan.csv > lathaan.json
csvtojson quartz.csv > quartz.json
csvtojson mavro.csv > mavro.json
csvtojson futcoin.csv > futcoin.json
csvtojson batcoin.csv > batcoin.json
csvtojson clinton.csv > clinton.json
csvtojson lepen.csv > lepen.json
csvtojson pokecoin.csv > pokecoin.json
csvtojson karmacoin.csv > karmacoin.json
csvtojson draftcoin.csv > draftcoin.json
csvtojson dubstep.csv > dubstep.json
csvtojson qora.csv > qora.json
csvtojson bitgem.csv > bitgem.json
csvtojson shacoin.csv > shacoin.json
csvtojson safecoin.csv > safecoin.json
csvtojson rcoin.csv > rcoin.json
csvtojson richcoin.csv > richcoin.json
csvtojson skeincoin.csv > skeincoin.json
csvtojson thecreed.csv > thecreed.json
csvtojson royalcoin.csv > royalcoin.json
csvtojson shellcoin.csv > shellcoin.json
csvtojson cybercoin.csv > cybercoin.json
csvtojson microcoin.csv > microcoin.json
csvtojson eggcoin.csv > eggcoin.json
csvtojson cashme.csv > cashme.json
csvtojson ocow.csv > ocow.json
csvtojson darklisk.csv > darklisk.json
csvtojson bongger.csv > bongger.json
csvtojson rhfcoin.csv > rhfcoin.json
csvtojson netbit.csv > netbit.json
csvtojson soulcoin.csv > soulcoin.json
csvtojson x2.csv > x2.json
csvtojson shellpay.csv > shellpay.json
csvtojson tyrocoin.csv > tyrocoin.json
csvtojson huncoin.csv > huncoin.json
csvtojson teamup.csv > teamup.json
csvtojson mmxvi.csv > mmxvi.json
csvtojson ugain.csv > ugain.json
csvtojson gambleo.csv > gambleo.json
csvtojson golfcoin.csv > golfcoin.json
csvtojson xaucoin.csv > xaucoin.json
csvtojson asiccoin.csv > asiccoin.json
csvtojson pinkdog.csv > pinkdog.json
csvtojson operand.csv > operand.json
csvtojson wowcoin.csv > wowcoin.json
csvtojson btcgold.csv > btcgold.json
csvtojson regacoin.csv > regacoin.json
csvtojson avoncoin.csv > avoncoin.json
csvtojson uncoin.csv > uncoin.json
